/* 
    PRODUCT ACTION TYPE
*/
export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_BEGIN = 'FETCH_PRODUCT_BEGIN';
export const FETCH_PRODUCT_SUCESS = 'FETCH_PRODUCT_SUCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

/*
    CATEGORY ACTION TYPE
*/
export const FETCH_CATEGORIES_BEGIN = 'FETCH_CATEGORIES_BEGIN';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

/* 
    CART
*/
export const LOAD_CART = 'LOAD_CART';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const UPDATE_CART = 'UPDATE_CART';

/* 
    REGISTER
*/
export const REGISTER_BENGIN = 'REGISTER_BENGIN';
export const REGISTER_SUCESS = 'REGISTER_SUCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN';
export const USER_LOGIN_SUCESS = 'USER_LOGIN_SUCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT_BEGIN = 'USER_LOGOUT_BEGIN';
export const USER_LOGOUT_SUCESS = 'USER_LOGOUT_SUCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const CHECK_USER_LOGGEDIN = 'CHECK_USER_LOGGEDIN';